stages:
- name: Compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: myclau/demo-rancher-pipeline:latest
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
