apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: demo-rancher-pipeline
  namespace: demo-rancher-pipeline
  
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-demo-rancher-pipeline-demo-rancher-pipeline
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2018-11-22T08:34:30.000Z
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-demo-rancher-pipeline-demo-rancher-pipeline
    spec:
      containers:
      - image: myclau/demo-rancher-pipeline:latest
        imagePullPolicy: Always
        name: demo-rancher-pipeline
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 500m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: docker-hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
